// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChhSxWnoR2q3PEndD4yYggPDdAmPCyUsA',
    appId: '1:1068736385690:web:e9bf96bc246a5d083cc523',
    messagingSenderId: '1068736385690',
    projectId: 'flute-1',
    authDomain: 'flute-1.firebaseapp.com',
    databaseURL: 'https://flute-1-default-rtdb.firebaseio.com',
    storageBucket: 'flute-1.appspot.com',
    measurementId: 'G-1RZHM3LJ3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpfuCAXdguTCGd9-P8oTYETaM_Z_Wl22o',
    appId: '1:1068736385690:android:5e20d3e31216ddea3cc523',
    messagingSenderId: '1068736385690',
    projectId: 'flute-1',
    databaseURL: 'https://flute-1-default-rtdb.firebaseio.com',
    storageBucket: 'flute-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutJI_V8RogayCq0RXJ3laZVRNXMg6wpU',
    appId: '1:1068736385690:ios:a58f70536852d8263cc523',
    messagingSenderId: '1068736385690',
    projectId: 'flute-1',
    databaseURL: 'https://flute-1-default-rtdb.firebaseio.com',
    storageBucket: 'flute-1.appspot.com',
    iosClientId: '1068736385690-mgq9akbi37ljk2i44l8uopd3uj6s20bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.proton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAutJI_V8RogayCq0RXJ3laZVRNXMg6wpU',
    appId: '1:1068736385690:ios:a58f70536852d8263cc523',
    messagingSenderId: '1068736385690',
    projectId: 'flute-1',
    databaseURL: 'https://flute-1-default-rtdb.firebaseio.com',
    storageBucket: 'flute-1.appspot.com',
    iosClientId: '1068736385690-mgq9akbi37ljk2i44l8uopd3uj6s20bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.proton',
  );
}
